### ISSUE TITLE
Moving Stickers

### ISSUE THREAD

**Issue by ScathachSkadi** [yymin1022/KakaoEmoticon2TelegramSticker#8]
움직이는 이모티콘은 스티커로 만들면 안 움직이던데 움직이게 만들 수 있나요?

**Comment by yymin1022** [comment]
@ScathachSkadi 
안녕하세요, 움직이는 이모티콘의 경우는 카카오 자체 방식으로 암호화가 되어있어 움직이는 스티커 형태로 추출이 어렵습니다.
현재 구현은 웹상에서 확인 가능한 첫 프레임만을 따서 스티커팩으로 생성하도록 되어있습니다.

**Comment by ScathachSkadi** [comment]
감사합니다.
